# Generated by Django 6.0.2 on 2026-02-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_email', models.EmailField(max_length=254)),
                ('brand_password', models.CharField(max_length=128)),
                ('brand_photo', models.FileField(upload_to='brand/photo/')),
                ('brand_proof', models.FileField(upload_to='brand/proof/')),
                ('brand_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_name', models.CharField(max_length=100)),
                ('influencer_email', models.EmailField(max_length=254)),
                ('influencer_password', models.CharField(max_length=128)),
                ('influencer_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=128)),
                ('user_address', models.TextField()),
                ('user_photo', models.FileField(upload_to='user/photo/')),
                ('user_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tbl_category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_district',
            name='district_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_place',
            name='place_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('event_details', models.TextField()),
                ('event_promocode', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_brand')),
                ('event_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_influencer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_description', models.TextField()),
                ('post_file', models.FileField(upload_to='post/files/')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_influencer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_brand')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_post',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product'),
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField()),
                ('cart_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_status', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_status', models.CharField(max_length=50)),
                ('from_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='server.tbl_brand')),
                ('from_influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_influencer_requests', to='server.tbl_influencer')),
                ('to_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='server.tbl_brand')),
                ('to_influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_influencer_requests', to='server.tbl_influencer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_category')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_subcategory'),
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField()),
                ('review_comment', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_influencer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=200)),
                ('complaint_content', models.TextField()),
                ('complaint_reply', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user'),
        ),
    ]
