# Generated by Django 6.0.2 on 2026-02-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_tbl_brand_tbl_comment_tbl_comment_reply_tbl_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place'),
        ),
        migrations.AlterField(
            model_name='tbl_brand',
            name='brand_photo',
            field=models.FileField(upload_to='Assets/brand/photo/'),
        ),
        migrations.AlterField(
            model_name='tbl_brand',
            name='brand_proof',
            field=models.FileField(upload_to='Assets/brand/proof/'),
        ),
    ]
