# Generated by Django 6.0.2 on 2026-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tbl_user_place_alter_tbl_brand_brand_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(upload_to='Assets/user/photo/'),
        ),
    ]
