# Generated by Django 6.0.2 on 2026-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_influencer',
            name='influencer_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
