# Generated by Django 6.0.2 on 2026-02-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_tbl_influencer_influencer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_influencer',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place'),
        ),
    ]
