# Generated by Django 6.0.2 on 2026-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_tbl_influencer_influencer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
