# Generated by Django 6.0.2 on 2026-02-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_tbl_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
