# Generated by Django 6.0.2 on 2026-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='cart_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='cart_status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
