# Generated by Django 6.0.2 on 2026-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_rename_link_name_tbl_link_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_status',
            field=models.IntegerField(default=0),
        ),
    ]
