# Generated by Django 6.0.2 on 2026-03-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_tbl_request_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='from_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='server.tbl_brand'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='from_influencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_influencer_requests', to='server.tbl_influencer'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='request_status',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='to_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='server.tbl_brand'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='to_influencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_influencer_requests', to='server.tbl_influencer'),
        ),
    ]
