# Generated by Django 5.2.12 on 2026-03-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_remove_tbl_chat_room_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_brand')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_influencer')),
            ],
            options={
                'unique_together': {('brand', 'influencer')},
            },
        ),
        migrations.CreateModel(
            name='tbl_chat_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('sender_type', models.CharField(max_length=20)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_brand')),
                ('influencer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_influencer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_chat_room')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_status', models.CharField(default='0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='server.tbl_brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_chat_room')),
                ('to_influencer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_influencer_requests', to='server.tbl_influencer')),
            ],
        ),
    ]
