# Generated by Django 5.2.12 on 2026-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_tbl_event_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_event_apply',
        ),
    ]
