# Generated by Django 5.2.12 on 2026-03-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_rename_user_tbl_complaint_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaint',
            old_name='customer',
            new_name='user',
        ),
    ]
