# Generated by Django 6.0.2 on 2026-02-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_tbl_event_brand_remove_tbl_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_email', models.EmailField(max_length=254)),
                ('brand_password', models.CharField(max_length=128)),
                ('brand_photo', models.FileField(upload_to='brand/photo/')),
                ('brand_proof', models.FileField(upload_to='brand/proof/')),
                ('brand_link', models.CharField(max_length=1000)),
                ('brand_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('event_details', models.TextField()),
                ('event_promocode', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_brand')),
                ('event_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_description', models.TextField()),
                ('post_file', models.FileField(upload_to='post/files/')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_influencer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_post')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_post'),
        ),
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_brand')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_post',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product'),
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField()),
                ('cart_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_status', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_influencer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_status', models.CharField(max_length=50)),
                ('from_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='server.tbl_brand')),
                ('from_influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_influencer_requests', to='server.tbl_influencer')),
                ('to_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='server.tbl_brand')),
                ('to_influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_influencer_requests', to='server.tbl_influencer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField()),
                ('review_comment', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product')),
            ],
        ),
    ]
