# Generated by Django 6.0.2 on 2026-03-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_tbl_cart_cart_price_alter_tbl_cart_cart_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_link',
            old_name='link_name',
            new_name='link_url',
        ),
    ]
