# Generated by Django 6.0.2 on 2026-03-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_tbl_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_product'),
        ),
    ]
