# Generated by Django 6.0.2 on 2026-03-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_tbl_address_tbl_booking_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tbl_address',
            name='state',
        ),
    ]
