# Generated by Django 5.2.12 on 2026-03-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_alter_tbl_address_id_alter_tbl_admin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_chat_room',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='tbl_chat_room',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='tbl_chat_room',
            name='request',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='from_brand',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='from_influencer',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='to_brand',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='to_influencer',
        ),
        migrations.DeleteModel(
            name='tbl_chat_message',
        ),
        migrations.DeleteModel(
            name='tbl_chat_room',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
