# Generated by Django 5.2.12 on 2026-03-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_tbl_chat_room_tbl_chat_message_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_status', models.CharField(default='0', max_length=50)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
