# Generated by Django 5.2.12 on 2026-03-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_tbl_event_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaint',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_title',
            field=models.CharField(max_length=50),
        ),
    ]
