# Generated by Django 5.2.12 on 2026-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_rename_customer_tbl_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='payment_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
